version: "3.3"
services:
  queue-radiology:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8030:80"
      - "5175:5173"
    container_name: queue-radiology
    restart: always
    logging:
      options:
        max-size: 1g
    volumes:
      - ./:/app/
    working_dir: /app/
    network_mode: bridge